;;; load file used by OM
(flet ((load-compile (path)
	 (if (member :om-deliver *features*)
	     (om::compile&load (make-pathname :type nil :defaults path))
	     (load (compile-file path)))))
  (let ((*default-pathname-defaults* *load-truename*))
    (load-compile "package.lisp")
    (load-compile "menu.lisp")
    (load-compile "define-box.lisp")
    (load-compile "file-dialog.lisp")
    (load-compile "pprint-define-box.lisp")))
